# storageclass
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: pd.csi.storage.gke.io # 외부프로비저너 
parameters:
  type: pd-standard # 표준 영구 디스크 
volumeBindingMode: WaitForFirstConsumer # 디스크 생성 시점
                                        # Immediate # 즉시 생성 
---
# pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow
---
# pod
kind: Pod
apiVersion: v1
metadata:
  name: mongo
spec:
  # mongo 컨테이너 정의 
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
          name: "mongo-client"
      volumeMounts:
        - mountPath: "/data/db" # 컨테이너 개발자가 정한다. 
          name: mongo-data-vol # 볼륨의 정의에서 구성한 이름과 일치
  # 볼륨의 정의
  volumes:
    - name: mongo-data-vol
      persistentVolumeClaim:
        claimName: mongo-data-pvc # 앞서 생성한 pvc 이름과 일치
---
