mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.130.0
config:
  exporters:
    loki:
      endpoint: http://my-lgtm-loki-distributor.lgtm:3100/loki/api/v1/push
    prometheusremotewrite:
      endpoint: http://my-lgtm-mimir-nginx.lgtm/api/v1/push
    otlp/tempo:
      endpoint: my-lgtm-tempo-distributor.lgtm:4317
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: []
        exporters: [loki]
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [prometheusremotewrite]
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlp/tempo]